import os
from src.abstraction.types.grid import Grid
from src.abstraction.algorithms.discretizer import DiscretizationAlgorithm
from src.abstraction.modules.wrappers import PlantWrapper, ControllerWrapper
from src.abstraction.semantics.labeling import LabelingGrammar

def run_modular_abstraction(plant, controller, grid_preset='medium'):
    """
    The High-Level Orchestrator.
    1. Wraps your Concrete Models (Plant/Controller).
    2. Runs the Generic Discretization Algorithm.
    3. Exports the Modular .prism file.
    """
    print(f"\n[Pipeline] Starting Modular Abstraction (Preset: {grid_preset})...")
    
    # 1. Setup
    grid = Grid(preset=grid_preset)
    algo = DiscretizationAlgorithm(grid)
    
    # 2. Run Abstraction (The Heavy Lifting)
    # A. Physics Module
    print("[Pipeline] Module 1/2: Vehicle Plant")
    plant_imdp = algo.run(PlantWrapper(plant), name="Plant")
    
    # B. Logic Module
    print("[Pipeline] Module 2/2: AEBS Controller")
    ctrl_imdp = algo.run(ControllerWrapper(controller), name="Controller")
    
    # 3. Export to PRISM
    # We consolidate them into one file with the synchronization logic
    output_path = "artifacts/modular_system.prism"
    _export_composed_system(plant_imdp, ctrl_imdp, controller, grid, output_path)
    
    return output_path

def _export_composed_system(plant_imdp, ctrl_imdp, controller, grid, filename):
    """
    Helper to write the Parallel Composition logic.
    """
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    with open(filename, 'w') as f:
        f.write("// --- MODULAR AEBS MODEL (Generated by Pipeline) ---\n")
        f.write("mdp\n\n")
        
        # 1. Globals (Shared Memory)
        f.write("global t : [1..3] init 1; // Turn: 1=Phys, 2=Perc, 3=Ctrl\n")
        f.write("global u : [0..2] init 0; // Action: 0=Coast, 1=Brake, 2=Emerg\n\n")
        
        # 2. Module: Synchronization
        f.write("module Turn\n")
        f.write("    [time_step] (t=1) -> (t'=2);\n")
        f.write("    [perceive]  (t=2) -> (t'=3);\n")
        f.write("    [control]   (t=3) -> (t'=1);\n")
        f.write("endmodule\n\n")
        
        # 3. Module: Plant (From IMDP)
        f.write(plant_imdp.to_prism_module("Plant", sync_label="time_step", state_var="s", action_var="u"))
        
        # 4. Module: Perception (Placeholder / Passthrough)
        f.write("\nmodule Perception\n")
        f.write(f"    y : [0..{grid.total_states-1}] init 0;\n")
        f.write("    [perceive] true -> (y'=s);\n")
        f.write("endmodule\n")

        # 5. Module: Controller (From IMDP)
        # Note: We manually inject the 'u' update logic since the Generic IMDP 
        # stores the transition Target ID, which corresponds to the Action ID here.
        f.write("\nmodule Controller\n")
        f.write(f"    // Logic updates global u based on local y\n")
        
        # We sort to ensure deterministic file output
        for src in sorted(ctrl_imdp.transitions.keys()):
            actions = ctrl_imdp.transitions[src]
            for _, targets in actions.items():
                 # For the controller wrapper, the target_id IS the decision (u)
                 decision = targets[0].target_id 
                 f.write(f"    [control] (y={src}) -> (u'={decision});\n")
        f.write("endmodule\n")

        # 6. Labels (Semantics)
        _write_labels(f, grid, controller)

    print(f"[Pipeline] SUCCESS. Model saved to {filename}")

def _write_labels(f, grid, controller):
    grammar = LabelingGrammar(controller)
    label_map = {"crash": [], "safe": [], "braking": [], "emergency": []}
    
    import itertools
    for idx in itertools.product(*[range(d) for d in grid.shape]):
        flat_id = grid.get_flat_index(idx)
        center = grid.index_to_cell_center(idx)
        
        tags = grammar.get_labels(center)
        for t in tags: 
            if t in label_map:
                label_map[t].append(str(flat_id))
        
    f.write("\n// --- SEMANTIC LABELS ---\n")
    for name, states in label_map.items():
        if states:
            f.write(f'label "{name}" = (s={" | s=".join(states)});\n')